### ISSUE TITLE
Unable to analyze it

### ISSUE THREAD

**Issue by kingsleyluoxin** [msgpeek/proxbbe#1]
I have made it to run "pin -t traceer.so -- wget https://json.com" and got a trace 
file. However, while analyzing it using the Ruby script, I met a Nil Error, i.e., 
/proxbbe/analyzer/taint_engine/taint_engine.rb:725:in `handle_cmpsx': undefined method `[]' for nil:NilClass (NoMethodError)
Is this due to the unhandled cmpsx instruction?

**Comment by disasmwinnie** [comment]
The cmpsx is actually handled in [taint_engine.rb:725](https://github.com/msgpeek/proxbbe/blob/master/analyzer/taint_engine/taint_engine.rb#L724). That's sounds like an ordinary bug. The InstructionState object passed to ``handle_cmpsx`` has either malformed (memory) operands or, which is more likely, is nil itself.
Either way, I assume the error is happening during the parsing beforehand. Will need to debug this properly.

Can you please give me some more info about your system? Distro is usually enough, so I can reproduce the case. Alternatively, the trace gzipped and uploaded somewhere to Gdrive or alike would accelerate things. 

An important note, which likely has nothing to do with the actual bug: I think you will not get any usable result using HTTPS. The pin-tracer is looking for socket reading syscalls which, in case of HTTPS are happening, but contain encrypted payload. I took json.org as an example because it was one of the few websites still available via HTTP (back then actually only via HTTP). 

a) Try http://json.org or b) in case you are fluent with PIN, you will have to adjust the trace to look for GnuTLS library calls (not syscalls!) which return you the decrypted packet payload. I never dealt with OpenSSL and GnuTLS calls, since it was outside my PoC scope, I am pretty sure there are pintools on $public_repo which dump encrypted payload.

**Comment by kingsleyluoxin** [comment]
Thank you so much for your answer. I shall first try it on my own. If errors could still not be handled, then I will turn to you :)

**Comment by kingsleyluoxin** [comment]
https://pan.baidu.com/s/15_5iDeT6eFK1BfgEwDBQqQ 
extraction code: sfuz 

By the way, this is the trace I got :)
@msgpeek

**Comment by disasmwinnie** [comment]
OK... Google Translate is not working with Baidu and I don't know Chinese, I have no idea how to download this file. I tried something that looks like a download button, but it gave me deb/rpm packages or guided me towards smartphone app stores. I'm afraid I will need some screenshot guidance on where to click, or you'll find a website for the upload which works in English.

**Comment by kingsleyluoxin** [comment]
Sorry for my carelessness :(, I have uploaded it onto GoogleDrive. 
https://drive.google.com/open?id=1jYS_p62e6rnD9b_AZTZXO5uuzn1EE5dR

**Comment by disasmwinnie** [comment]
No worries... I don't know why Google Translate is failing, myself. I'm glad we could make it work. I'll try to reproduce it and find the bug during the next days. Thanks a lot for providing me the trace!

**Comment by kingsleyluoxin** [comment]
:)

**Comment by kingsleyluoxin** [comment]
:)

**Comment by disasmwinnie** [comment]
It looks like you are using the wrong PIN version. The mappings of instructions to a variable ``iclass``, which I use to detect the actual action in the taint engine, change on every PIN version. 

Please confirm that your are using pin-3.2-81205 and re-record the trace.

**Comment by kingsleyluoxin** [comment]
Thanks so much. I shall try it again this time. Sorry for the delayed reply :)

**Comment by kingsleyluoxin** [comment]
I am trying to use 3.2 version. However, it goes with Error "Source/pin/base_l/sysfuncs_linux.cpp: IA32E_CHECK: 135: assertion failed: result != -1". So if I want it to run on version 3.12, do I have to modify the code for iclass ?

**Comment by kingsleyluoxin** [comment]
:) Thanks so much for your help. I have modified the iclass number in ruby scripts, and it has run as expected :) @msgpeek

**Comment by disasmwinnie** [comment]
Glad it worked out. Let me know if you have any further questions.
Meanwhile I re-prioritized the [iclass-number](https://github.com/msgpeek/proxbbe/issues/2) issue and will (hopefully) be able to tackle that soon.
