### ISSUE TITLE
On ThreadTrace and PIN_GetThreadData

### ISSUE THREAD

**Issue by kingsleyluoxin** [msgpeek/proxbbe#3]
Hello, when I read this piece of codes, I felt confused. I am wondering if you can help me understand this. 
```c
ThreadTrace*
get_tls(THREADID tid)
{
  return static_cast<ThreadTrace*>(PIN_GetThreadData(tls_key, tid));
}
```
When using static_cast to cast threadData to pre-defined ThreadTrace, are we supposed to following some specific rules to define ThreadTrace, or it can be any kind of structs?

**Comment by disasmwinnie** [comment]
In case this is still relevant...

This has something todo with multi-threading support of my PINtool.  PIN's TLS (Thread Local Storage) can be used to store some pointer (or other integer/data) per thread. My thread-specific data is a pointer to a ThreadTrace object. I use the THREADID to identify different threads. This ID is provided by PIN to identify the currently running thread.

Since the PIN_GetThreadData returns a void pointer, (see [docs](https://software.intel.com/sites/landingpage/pintool/docs/81205/Pin/html/group__PIN__THREAD__API.html#ga54b958f9981cd2b6de9eb442d8de85c4)) and, I know what pointer I stored there before, I do the static cast.

Generally, you can use TLS to store what ever makes sense for your PINtool. In my case I record traces per thread. Therefore, every thread-specific TLS stores a pointer to the ThreadTrace struct. The struct is defined in [proxbbe_tracer.h](https://github.com/msgpeek/proxbbe/blob/141d01811fe148cf2fd39a80dbf12c5e150d5a0c/tracer/proxbbe_tracer.h#L75) and is used to hold all data structres, I need to store the trace for any particular thread.

If you want to understand how to write PINtools, the [user guide](https://software.intel.com/sites/landingpage/pintool/docs/81205/Pin/html/index.html) is an excellent source. There is also a section on [TLS](https://software.intel.com/sites/landingpage/pintool/docs/81205/Pin/html/index.html#InscountTLS).

Hope that helps.
