### ISSUE TITLE
Why callbacks cannot output information?

### ISSUE THREAD

**Issue by kingsleyluoxin** [msgpeek/proxbbe#4]
Hello, I am trying to write a similar tool like tracer in your proxbbe. However, I could not record information in my callbacks. I am wondering if it is mandatory to output information in p_finished callbacks. Can I use stdout to output information in my callbacks? 

e.g. INS_InsertCall(ins, IPOINT_AFTER, (AFUNPTR)cb ...)

Can I use stdout in cb?

**Comment by disasmwinnie** [comment]
Hi, 

the ``p_finished`` callback is not mandatory at all. It is my own function which is called at the very end of the whole pintool respectively after the program that was traced, has finished execution. I need it for my own pintool logic and I use it to close the JSON trace file. 

Regarding the second question, yes you can definitely use stdout in your pintool. 
You can and should use your prints to stdout in analysis function, in your case ``cb()``.
Understanding PIN's concept of instrumentation and analysis time is very important (see Intel's official tutorial on PIN). During instrumentation time you should collect and extract information with PIN's macro functions like ``INS_MemoryOperandCount``, ``INS_MemoryOperandIsRead``, etc. Then use that information and hand them over to your analysis function with, e.g., ``INS_InsertCall(ins, IPOINT_AFTER, (AFUNPTR)cb ...)``. As a rule of thumb, avoid using complex data types like cpp strings during instrumentation time, if you can. If you start doing heavy I/O operations like prints or file writes, you program might work, but it also might randomly crash and burn for no good reason. Don't mess around during instrumentation time!!!

The analysis time, which happens when your ``cb()`` function is executed, you can do complex analysis task, including writing to files or stdout. It will take it's time but should not mess with your execution. This is what it's made for.

Hope that helps.

**Comment by kingsleyluoxin** [comment]
Yes, it does help. Thanks so much. There is still another puzzle. I am trying to integrate taint analysis into my pintool. I am wondering at which point I can stop taint spreading.  Since few articles mentioned this when doing protocol reverse engineering, do you have any solution?

**Comment by disasmwinnie** [comment]
Sorry that this went under.
The simple answer is that you probably don't know. You would have to know (at least important parts of) the target,  through prior analysis.
